[project]
name = "mtl-cmd"
version = "0.1.0-pre_alpha.2"
description = "A helper process to format Master Tag List and Context Master Data for LS_DH_USJA_DDS 20471406"
readme = "README.md"
requires-python = ">=3.11.3"
license = "MIT"
license-files = ["LICENSE.*"]
authors = [
  { name = "Raymond Comeau", email = "raymond.comeau@milliporesigma.com" },
]
maintainers = [
  { name = "Raymond Comeau", email = "raymond.comeau@milliporesigma.com" }
]
keywords = ["CMD", "DDS", "Jaffrey", "MTL", "USJA"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]
dependencies = [
  "et_xmlfile>=2.0.0",
  "numpy>=2.4.0",
  "openpyxl>=3.1.5",
  "xlwings>=3.1",
  "pandas>=2.3.3",
  "pillow>=12.0.0",
  "python-dateutil>=2.9.0.post0",
  "pytz>=2025.0",
  "setuptools>=65.5.0",
  "six>=1.17.0",
  "ttkbootstrap>=1.20.0",
  "tzdata>=2025.3",
]

[project.urls]
"Bug Tracker" = "http://157.93.24.68/M268816/WAVE/issues"
Changelog = "http://157.93.24.68/M268816/WAVE/blob/main/CHANGELOG.md"
# Documentation = "https://readthedocs.org"
# Homepage = "https://example.com"
Repository = "https://157.92.24.68/M268816/WAVE"

[project.optional-dependencies]

[build-system]
requires = ["setuptools >= 65.0.5"]
build-backend = "setuptools.build_meta"
