[project]
name = "m-wave"
version = "0.1.0dev6"
description = "An application that helps Jaffrey PI developers with configurations."
readme = "README.md"
requires-python = ">=3.11.3"
license = "MIT"
license-files = ["LICENSE.*"]
authors = [
  { name = "Raymond Comeau", email = "raymond.comeau@milliporesigma.com" },
]
maintainers = [
  { name = "Raymond Comeau", email = "raymond.comeau@milliporesigma.com" }
]
keywords = ["CMD", "DDS", "Jaffrey", "MTL", "USJA"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Operating System :: Microsoft :: Windows",
  "Intended Audience :: Developers",
]

dependencies = [
  "et_xmlfile>=2.0.0",
  "numpy>=2.0.0",
  "openpyxl>=3.1.5",
  "pandas>=2.2.0",
  "pillow>=10.0.0",
  "python-dateutil>=2.9.0.post0",
  "pytz>=2024.1",
  "six>=1.17.0",
  "ttkbootstrap>=2.1.0",
  "tzdata>=2024.1",
  "xlwings>=0.31.0",
  "datacompy>=0.13.0",
  "pywin32>=306; platform_system == 'Windows'",
]

[project.scripts]
m-wave = "m_wave.__main__:main"

[project.urls]
"Bug Tracker" = "http://157.93.24.68/M268816/WAVE/issues"
Changelog = "http://157.93.24.68/M268816/WAVE/blob/main/CHANGELOG.md"
Repository = "https://157.92.24.68/M268816/WAVE"

[dependency-groups]
dev = [
  "bandit>=1.7.0",
  "pytest>=8.0.0",
  "pytest-cov>=5.0.0",
  "pyinstaller>=6.0.0",
  "pip-audit>=2.7.0",
]

[build-system]
requires = ["setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
m_wave = [
  "assets/**/*",
]

[tool.uv]
package = true