# Copyright 2026 Merck KGaA, Darmstadt, Germany and/or its affiliates.
# All rights reserved
# Author: Raymond Comeau, MilliporeSigma Data Systems Technician, Jaffrey NH
# This tool was created with the help of AI.

"""
MTL WavePack pdf report layout.

This is the ReportLab equivalent of ``mtl_comparison_report_template.html``.
It owns the MTL report's data contract and its body layout; the document
shell, styles, and reusable components come from ``m_wave.core.pdf_report``.
"""

from __future__ import annotations

# stdlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# third party
from reportlab.platypus import Flowable, KeepTogether, Paragraph, Spacer

# local
from m_wave.core.pdf_reporting import (
    Metrics,
    PDFReportData,
    PDFReportStatus,
    ReportStyles,
    chart_image,
    data_table,
    empty_state,
    format_datetime,
    metric_grid,
    note_box,
    section_heading,
    shorten_path,
    status_banner,
    thousands,
)

# How many individual differences are listed in the PDF. The full set belongs
# in the CSV export; a PDF with ten thousand mismatch rows helps nobody.
DIFFERENCE_SAMPLE_LIMIT = 25
KEY_SAMPLE_LIMIT = 25


# APPENDING


@dataclass
class UpsertIssue:
    """
    A validation problem that stopped ot qualified the upsert.

    ''check'' names the guard that fired, ''detail'' is what the user needs to
    fix, ''severity'' drives the color in the findings table.
    """

    check: str
    detai: str
    severity: str = "error"


@dataclass
class MTLAppendReportData(PDFReportData):
    """
    MTL append / upsert report.

    Inherits ``title``, ``report_id``, ``user``, ``created_date``, ``status``,
    ``subtitle``, and ``chart_paths`` from ``PDFReportData``.
    """

    mtl_source: Path = Path()
    pib_source: Path = Path()
    worksheet_name: str | None = None
    filter_string: str | None = None

    rows_in_mtl_before: int = 0
    rows_in_pib: int = 0
    rows_in_mtl_after: int = 0
    rows_updated: int = 0
    rows_appended: int = 0

    updated_keys: list[str] = field(default_factory=list)
    appended_keys: list[str] = field(default_factory=list)
    issues: list[UpsertIssue] = field(default_factory=list)

    key_columns: list[str] = field(default_factory=list)
    artifacts: list[tuple[str, str]] = field(default_factory=list)

    filter_action: str | None = None
    written_to_mtl: bool = False
    mtl_output_name: str | None = None

    # -- derived values -----------------------------------------------------

    @property
    def rows_changed(self) -> int:
        return self.rows_updated + self.rows_appended

    @property
    def rows_untouched(self) -> int:
        """MTL rows the PI Builder file had nothing to say about."""
        return max(self.rows_in_mtl_before - self.rows_updated, 0)

    @property
    def row_delta(self) -> int:
        """Net change in table height. Should always equal rows_appended."""
        return self.rows_in_mtl_after - self.rows_in_mtl_before

    @property
    def row_count_reconciles(self) -> bool:
        """
        An upsert adds exactly one row per new key and changes no row count
        for an updated key. If this is False the numbers disagree with the
        arithmetic and the reader needs to know.
        """
        return self.row_delta == self.rows_appended

    # -- base-class hooks ---------------------------------------------------

    @property
    def metadata_rows(self) -> list[tuple[str, str]]:
        rows = [
            ("Report ID", self.report_id),
            ("Generated", format_datetime(self.created_date)),
            ("Generated by", self.user),
        ]

        if self.worksheet_name:
            rows.append(("Worksheet", self.worksheet_name))

        rows.append(("MTL source", shorten_path(self.mtl_source)))
        rows.append(("PI Builder source", shorten_path(self.pib_source)))

        if self.key_columns:
            rows.append(("Match keys", ", ".join(self.key_columns)))

        rows.append(("Filter", self.filter_string or "None"))

        return rows

    @property
    def status_message(self) -> str:
        if self.status is PDFReportStatus.PASS:
            target = "the MTL" if self.written_to_mtl else "the CSV export only"
            return (
                f"{thousands(self.rows_updated)} rows updated and "
                f"{thousands(self.rows_appended)} rows appended, written to "
                f"{target}."
            )

        if self.status is PDFReportStatus.FAIL:
            return (
                "The append was stopped before any data was written. "
                "Resolve the findings below and run it again."
            )

        if self.status is PDFReportStatus.ERRORED:
            return (
                "The append did not finish. The MTL may not reflect the "
                "counts below, so verify the output file before using it."
            )

        return "No append result was recorded for this run."

    # -- layout -------------------------------------------------------------

    def build_elements(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        """Assemble the append report body."""
        elements: list[Flowable] = [
            status_banner(styles, self.status, self.status_message, width),
            Spacer(1, Metrics.GAP_SECTION),
        ]

        elements.extend(self._summary_section(styles, width))
        elements.extend(self._issue_section(styles, width))
        elements.extend(self._row_accounting_section(styles, width))
        elements.extend(self._key_section(styles, width))
        elements.extend(self._artifact_section(styles, width))

        elements.append(Spacer(1, Metrics.GAP_SECTION))
        elements.append(note_box(styles, self._closing_note(), width))

        return elements

    # -- sections -----------------------------------------------------------

    def _summary_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        metrics = [
            ("Rows updated", thousands(self.rows_updated)),
            ("Rows appended", thousands(self.rows_appended)),
            ("Rows unchanged", thousands(self.rows_untouched)),
            ("MTL rows after", thousands(self.rows_in_mtl_after)),
        ]

        return [
            section_heading(styles, "Summary"),
            Spacer(1, Metrics.GAP_SECTION),
            metric_grid(styles, metrics, width, columns=4),
            Spacer(1, Metrics.GAP),
        ]

    def _issue_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        heading = section_heading(styles, "Findings")

        if not self.issues:
            return [
                Spacer(1, Metrics.GAP_HEADING),
                KeepTogether(
                    [
                        heading,
                        Spacer(1, 10),
                        empty_state(
                            styles,
                            "No problems were found. The column schema, the key "
                            "columns, and key uniqueness all passed, and the "
                            "result contained no duplicate keys.",
                        ),
                    ]
                ),
            ]

        rows = [
            [
                issue.check,
                issue.detail,
                Paragraph(
                    issue.severity.capitalize(),
                    styles.severity_style(issue.severity),
                ),
            ]
            for issue in self.issues
        ]

        table = data_table(
            styles,
            headers=["Check", "What was found", "Severity"],
            rows=rows,
            width=width,
            column_ratios=[1.8, 4.2, 1.0],
        )

        return [
            Spacer(1, Metrics.GAP_HEADING),
            heading,
            Spacer(1, 10),
            table,
        ]

    def _row_accounting_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        rows = [
            ["MTL rows before the append", thousands(self.rows_in_mtl_before)],
            ["PI Builder rows supplied", thousands(self.rows_in_pib)],
            ["Rows updated in place", thousands(self.rows_updated)],
            ["Rows appended as new", thousands(self.rows_appended)],
            ["Rows left untouched", thousands(self.rows_untouched)],
            ["MTL rows after the append", thousands(self.rows_in_mtl_after)],
        ]

        table = data_table(
            styles,
            headers=["Category", "Rows"],
            rows=rows,
            width=width,
            column_ratios=[4.0, 1.0],
            right_aligned=(1,),
        )

        elements: list[Flowable] = [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Row accounting"),
            Spacer(1, 10),
            table,
        ]

        # Surface an arithmetic disagreement rather than letting the reader
        # discover it by adding up the table themselves.
        if not self.row_count_reconciles:
            elements.append(Spacer(1, Metrics.GAP))
            elements.append(
                Paragraph(
                    f"The table grew by {thousands(self.row_delta)} row(s) but "
                    f"{thousands(self.rows_appended)} row(s) were reported as "
                    "appended. Verify the output file before using it.",
                    styles.severity_style("error"),
                )
            )

        return elements

    def _key_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        if not self.updated_keys and not self.appended_keys:
            return []

        rows: list[list[str]] = []

        for key in self.updated_keys[:KEY_SAMPLE_LIMIT]:
            rows.append([key, "Updated"])
        for key in self.appended_keys[:KEY_SAMPLE_LIMIT]:
            rows.append([key, "Appended"])

        table = data_table(
            styles,
            headers=["Record key", "Action"],
            rows=rows,
            width=width,
            column_ratios=[4.0, 1.4],
        )

        elements: list[Flowable] = [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Changed records"),
            Spacer(1, 10),
            table,
        ]

        hidden_updated = max(len(self.updated_keys) - KEY_SAMPLE_LIMIT, 0)
        hidden_appended = max(len(self.appended_keys) - KEY_SAMPLE_LIMIT, 0)

        if hidden_updated or hidden_appended:
            elements.append(Spacer(1, Metrics.GAP))
            elements.append(
                Paragraph(
                    f"{thousands(hidden_updated)} further updated row(s) and "
                    f"{thousands(hidden_appended)} further appended row(s) are "
                    "not listed here. The complete set is in the CSV exports.",
                    styles.metadata,
                )
            )

        return elements

    def _artifact_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        rows = [[name, description] for name, description in self.artifacts]

        if self.filter_action:
            rows.append(["Table filter", self.filter_action])

        if not rows:
            return []

        table = data_table(
            styles,
            headers=["File", "What it contains"],
            rows=rows,
            width=width,
            column_ratios=[2.2, 4.0],
        )

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Generated files"),
            Spacer(1, 10),
            table,
        ]

    def _closing_note(self) -> str:
        if self.status is not PDFReportStatus.PASS:
            return (
                "No changes were written to the MTL. The source MTL file was "
                "opened read-only, so it is unchanged on disk. Fix the "
                "findings above and run the append again."
            )

        if self.written_to_mtl and self.mtl_output_name:
            return (
                "The appended MTL was saved as a new file, "
                f"{self.mtl_output_name}. The original MTL was opened "
                "read-only and is unchanged. Review the appended workbook, "
                "then update the change log manually."
            )

        return (
            "The upsert completed and the result was exported to CSV. The "
            "original MTL was opened read-only and is unchanged. Review the "
            "CSV exports, then update the change log manually."
        )


__all__ = [
    "KEY_SAMPLE_LIMIT",
    "MTLAppendReportData",
    "UpsertIssue",
]


# COMPARING


@dataclass
class ComparisonRecord:
    """A single field-level disagreement between the MTL and PIB datasets."""

    record_key: str
    column: str
    mtl_value: Any
    pib_value: Any
    severity: str = "error"

    @property
    def mtl_display(self) -> str:
        return "\u2014" if self.mtl_value is None else str(self.mtl_value)

    @property
    def pib_display(self) -> str:
        return "\u2014" if self.pib_value is None else str(self.pib_value)


@dataclass
class ColumnDifferenceSummary:
    """Aggregate difference counts for one compared column."""

    column: str
    difference_count: int
    missing_from_mtl: int = 0
    missing_from_pib: int = 0


@dataclass
class MTLReportData(PDFReportData):
    """
    MTL vs PIB comparison report.

    Inherits ``title``, ``report_id``, ``user``, ``created_date``, ``status``,
    ``subtitle``, and ``chart_paths`` from ``PDFReportData``.
    """

    mtl_source: Path = Path()
    pib_source: Path = Path()
    records_compared: int = 0
    matching_records: int = 0
    non_matching_records: int = 0
    missing_from_mtl: int = 0
    missing_from_pib: int = 0
    column_summaries: list[ColumnDifferenceSummary] = field(default_factory=list)
    difference_samples: list[ComparisonRecord] = field(default_factory=list)
    csv_export_name: str | None = None

    # -- derived values -----------------------------------------------------

    @property
    def missing_records(self) -> int:
        return self.missing_from_mtl + self.missing_from_pib

    @property
    def match_rate(self) -> float | None:
        if not self.records_compared:
            return None
        return self.matching_records / self.records_compared * 100.0

    # -- base-class hooks ---------------------------------------------------

    @property
    def metadata_rows(self) -> list[tuple[str, str]]:
        """Masthead metadata, extended with the two compared sources."""
        return [
            ("Report ID", self.report_id),
            ("Generated", format_datetime(self.created_date)),
            ("Generated by", self.user),
            ("MTL source", shorten_path(self.mtl_source)),
            ("PIB source", shorten_path(self.pib_source)),
        ]

    @property
    def status_message(self) -> str:
        if self.status is PDFReportStatus.PASS:
            return "The datasets matched according to the configured comparison rules."
        if self.status is PDFReportStatus.FAIL:
            return (
                f"{thousands(self.non_matching_records)} records differ and should "
                "be reviewed."
            )
        if self.status is PDFReportStatus.ERRORED:
            return "The comparison did not finish. Results below may be incomplete."
        return "No comparison result was recorded for this run."

    # -- layout -------------------------------------------------------------

    def build_elements(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        """Assemble the MTL report body."""
        elements: list[Flowable] = []

        elements.append(status_banner(styles, self.status, self.status_message, width))
        elements.append(Spacer(1, Metrics.GAP_SECTION))

        elements.extend(self._summary_section(styles, width))
        elements.extend(self._chart_section(styles, width))
        elements.extend(self._column_section(styles, width))
        elements.extend(self._difference_section(styles, width))
        elements.extend(self._record_count_section(styles, width))

        elements.append(Spacer(1, Metrics.GAP_SECTION))
        elements.append(note_box(styles, self._closing_note(), width))

        return elements

    # -- sections -----------------------------------------------------------

    def _summary_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        metrics = [
            ("Records compared", thousands(self.records_compared)),
            ("Matching records", thousands(self.matching_records)),
            ("Differences", thousands(self.non_matching_records)),
            ("Missing records", thousands(self.missing_records)),
        ]

        return [
            section_heading(styles, "Summary"),
            Spacer(1, Metrics.GAP_SECTION),
            metric_grid(styles, metrics, width, columns=4),
            Spacer(1, Metrics.GAP),
        ]

    def _chart_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        path = self.chart_paths.get("differences_by_column")
        if path is None or not Path(path).exists():
            return []

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Differences by column"),
            Spacer(1, Metrics.GAP_SECTION),
            chart_image(Path(path), width),
            Spacer(1, Metrics.GAP),
        ]

    def _column_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        if not self.column_summaries:
            return []

        rows = [
            [
                summary.column,
                thousands(summary.difference_count),
                thousands(summary.missing_from_mtl),
                thousands(summary.missing_from_pib),
            ]
            for summary in self.column_summaries
        ]

        table = data_table(
            styles,
            headers=["Column", "Differences", "Missing from MTL", "Missing from PIB"],
            rows=rows,
            width=width,
            column_ratios=[3.0, 1.4, 1.6, 1.6],
            right_aligned=(1, 2, 3),
        )

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Column breakdown"),
            Spacer(1, 10),
            table,
        ]

    def _difference_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        heading = section_heading(styles, "Difference sample")

        if not self.difference_samples:
            return [
                Spacer(1, Metrics.GAP_HEADING),
                KeepTogether(
                    [
                        heading,
                        Spacer(1, 10),
                        empty_state(styles, "No differences were found."),
                    ]
                ),
            ]

        shown = self.difference_samples[:DIFFERENCE_SAMPLE_LIMIT]

        rows = [
            [
                record.record_key,
                record.column,
                record.mtl_display,
                record.pib_display,
                Paragraph(
                    record.severity.capitalize(),
                    styles.severity_style(record.severity),
                ),
            ]
            for record in shown
        ]

        table = data_table(
            styles,
            headers=["Record key", "Column", "MTL value", "PIB value", "Severity"],
            rows=rows,
            width=width,
            column_ratios=[1.6, 1.6, 1.5, 1.5, 1.0],
        )

        elements: list[Flowable] = [
            Spacer(1, Metrics.GAP_HEADING),
            heading,
            Spacer(1, 10),
            table,
        ]

        remaining = len(self.difference_samples) - len(shown)
        if remaining > 0:
            elements.append(Spacer(1, Metrics.GAP))
            elements.append(
                Paragraph(
                    f"Showing the first {thousands(len(shown))} of "
                    f"{thousands(len(self.difference_samples))} differences. "
                    f"{thousands(remaining)} further differences are in the "
                    "CSV export.",
                    styles.metadata,
                )
            )

        return elements

    def _record_count_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        rows = [
            ["Records compared", thousands(self.records_compared)],
            ["Matching records", thousands(self.matching_records)],
            ["Non-matching records", thousands(self.non_matching_records)],
            ["Missing from MTL", thousands(self.missing_from_mtl)],
            ["Missing from PIB", thousands(self.missing_from_pib)],
        ]

        table = data_table(
            styles,
            headers=["Category", "Count"],
            rows=rows,
            width=width,
            column_ratios=[4.0, 1.0],
            right_aligned=(1,),
        )

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Record counts"),
            Spacer(1, 10),
            table,
        ]

    def _closing_note(self) -> str:
        note = (
            "This PDF lists a sample of differences so it stays readable. "
            "The complete difference set is available in the accompanying "
            "CSV export"
        )
        if self.csv_export_name:
            return f"{note}: {self.csv_export_name}."
        return f"{note}."


__all__ = [
    "DIFFERENCE_SAMPLE_LIMIT",
    "ColumnDifferenceSummary",
    "ComparisonRecord",
    "MTLReportData",
]
