# Copyright 2026 Merck KGaA, Darmstadt, Germany and/or its affiliates.
# All rights reserved
# Author: Raymond Comeau, MilliporeSigma Data Systems Technician, Jaffrey NH
# This tool was created with the help of AI.

"""
MTL WavePack pdf report layout.

This is the ReportLab equivalent of ``mtl_comparison_report_template.html``.
It owns the MTL report's data contract and its body layout; the document
shell, styles, and reusable components come from ``m_wave.core.pdf_report``.
"""

from __future__ import annotations

# stdlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# third party
from reportlab.platypus import Flowable, KeepTogether, Paragraph, Spacer

# local
from m_wave.core.pdf_reporting import (
    Metrics,
    PDFReportData,
    PDFReportStatus,
    ReportStyles,
    chart_image,
    data_table,
    empty_state,
    format_datetime,
    metric_grid,
    note_box,
    section_heading,
    shorten_path,
    status_banner,
    thousands,
)

# How many individual differences are listed in the PDF. The full set belongs
# in the CSV export; a PDF with ten thousand mismatch rows helps nobody.
DIFFERENCE_SAMPLE_LIMIT = 25


@dataclass
class ComparisonRecord:
    """A single field-level disagreement between the MTL and PIB datasets."""

    record_key: str
    column: str
    mtl_value: Any
    pib_value: Any
    severity: str = "error"

    @property
    def mtl_display(self) -> str:
        return "\u2014" if self.mtl_value is None else str(self.mtl_value)

    @property
    def pib_display(self) -> str:
        return "\u2014" if self.pib_value is None else str(self.pib_value)


@dataclass
class ColumnDifferenceSummary:
    """Aggregate difference counts for one compared column."""

    column: str
    difference_count: int
    missing_from_mtl: int = 0
    missing_from_pib: int = 0


@dataclass
class MTLReportData(PDFReportData):
    """
    MTL vs PIB comparison report.

    Inherits ``title``, ``report_id``, ``user``, ``created_date``, ``status``,
    ``subtitle``, and ``chart_paths`` from ``PDFReportData``.
    """

    mtl_source: Path = Path()
    pib_source: Path = Path()
    records_compared: int = 0
    matching_records: int = 0
    non_matching_records: int = 0
    missing_from_mtl: int = 0
    missing_from_pib: int = 0
    column_summaries: list[ColumnDifferenceSummary] = field(default_factory=list)
    difference_samples: list[ComparisonRecord] = field(default_factory=list)
    csv_export_name: str | None = None

    # -- derived values -----------------------------------------------------

    @property
    def missing_records(self) -> int:
        return self.missing_from_mtl + self.missing_from_pib

    @property
    def match_rate(self) -> float | None:
        if not self.records_compared:
            return None
        return self.matching_records / self.records_compared * 100.0

    # -- base-class hooks ---------------------------------------------------

    @property
    def metadata_rows(self) -> list[tuple[str, str]]:
        """Masthead metadata, extended with the two compared sources."""
        return [
            ("Report ID", self.report_id),
            ("Generated", format_datetime(self.created_date)),
            ("Generated by", self.user),
            ("MTL source", shorten_path(self.mtl_source)),
            ("PIB source", shorten_path(self.pib_source)),
        ]

    @property
    def status_message(self) -> str:
        if self.status is PDFReportStatus.PASS:
            return "The datasets matched according to the configured comparison rules."
        if self.status is PDFReportStatus.FAIL:
            return (
                f"{thousands(self.non_matching_records)} records differ and should "
                "be reviewed."
            )
        if self.status is PDFReportStatus.ERRORED:
            return "The comparison did not finish. Results below may be incomplete."
        return "No comparison result was recorded for this run."

    # -- layout -------------------------------------------------------------

    def build_elements(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        """Assemble the MTL report body."""
        elements: list[Flowable] = []

        elements.append(status_banner(styles, self.status, self.status_message, width))
        elements.append(Spacer(1, Metrics.GAP_SECTION))

        elements.extend(self._summary_section(styles, width))
        elements.extend(self._chart_section(styles, width))
        elements.extend(self._column_section(styles, width))
        elements.extend(self._difference_section(styles, width))
        elements.extend(self._record_count_section(styles, width))

        elements.append(Spacer(1, Metrics.GAP_SECTION))
        elements.append(note_box(styles, self._closing_note(), width))

        return elements

    # -- sections -----------------------------------------------------------

    def _summary_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        metrics = [
            ("Records compared", thousands(self.records_compared)),
            ("Matching records", thousands(self.matching_records)),
            ("Differences", thousands(self.non_matching_records)),
            ("Missing records", thousands(self.missing_records)),
        ]

        return [
            section_heading(styles, "Summary"),
            Spacer(1, Metrics.GAP_SECTION),
            metric_grid(styles, metrics, width, columns=4),
            Spacer(1, Metrics.GAP),
        ]

    def _chart_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        path = self.chart_paths.get("differences_by_column")
        if path is None or not Path(path).exists():
            return []

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Differences by column"),
            Spacer(1, Metrics.GAP_SECTION),
            chart_image(Path(path), width),
            Spacer(1, Metrics.GAP),
        ]

    def _column_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        if not self.column_summaries:
            return []

        rows = [
            [
                summary.column,
                thousands(summary.difference_count),
                thousands(summary.missing_from_mtl),
                thousands(summary.missing_from_pib),
            ]
            for summary in self.column_summaries
        ]

        table = data_table(
            styles,
            headers=["Column", "Differences", "Missing from MTL", "Missing from PIB"],
            rows=rows,
            width=width,
            column_ratios=[3.0, 1.4, 1.6, 1.6],
            right_aligned=(1, 2, 3),
        )

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Column breakdown"),
            Spacer(1, 10),
            table,
        ]

    def _difference_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        heading = section_heading(styles, "Difference sample")

        if not self.difference_samples:
            return [
                Spacer(1, Metrics.GAP_HEADING),
                KeepTogether(
                    [
                        heading,
                        Spacer(1, 10),
                        empty_state(styles, "No differences were found."),
                    ]
                ),
            ]

        shown = self.difference_samples[:DIFFERENCE_SAMPLE_LIMIT]

        rows = [
            [
                record.record_key,
                record.column,
                record.mtl_display,
                record.pib_display,
                Paragraph(
                    record.severity.capitalize(),
                    styles.severity_style(record.severity),
                ),
            ]
            for record in shown
        ]

        table = data_table(
            styles,
            headers=["Record key", "Column", "MTL value", "PIB value", "Severity"],
            rows=rows,
            width=width,
            column_ratios=[1.6, 1.6, 1.5, 1.5, 1.0],
        )

        elements: list[Flowable] = [
            Spacer(1, Metrics.GAP_HEADING),
            heading,
            Spacer(1, 10),
            table,
        ]

        remaining = len(self.difference_samples) - len(shown)
        if remaining > 0:
            elements.append(Spacer(1, Metrics.GAP))
            elements.append(
                Paragraph(
                    f"Showing the first {thousands(len(shown))} of "
                    f"{thousands(len(self.difference_samples))} differences. "
                    f"{thousands(remaining)} further differences are in the "
                    "CSV export.",
                    styles.metadata,
                )
            )

        return elements

    def _record_count_section(
        self,
        styles: ReportStyles,
        width: float,
    ) -> list[Flowable]:
        rows = [
            ["Records compared", thousands(self.records_compared)],
            ["Matching records", thousands(self.matching_records)],
            ["Non-matching records", thousands(self.non_matching_records)],
            ["Missing from MTL", thousands(self.missing_from_mtl)],
            ["Missing from PIB", thousands(self.missing_from_pib)],
        ]

        table = data_table(
            styles,
            headers=["Category", "Count"],
            rows=rows,
            width=width,
            column_ratios=[4.0, 1.0],
            right_aligned=(1,),
        )

        return [
            Spacer(1, Metrics.GAP_HEADING),
            section_heading(styles, "Record counts"),
            Spacer(1, 10),
            table,
        ]

    def _closing_note(self) -> str:
        note = (
            "This PDF lists a sample of differences so it stays readable. "
            "The complete difference set is available in the accompanying "
            "CSV export"
        )
        if self.csv_export_name:
            return f"{note}: {self.csv_export_name}."
        return f"{note}."


__all__ = [
    "DIFFERENCE_SAMPLE_LIMIT",
    "ColumnDifferenceSummary",
    "ComparisonRecord",
    "MTLReportData",
]
