# Copyright 2026 Merck KGaA, Darmstadt, Germany and/or its affiliates.
# All rights reserved
#
# Author: Raymond Comeau, MilliporeSigma Data Systems Technician, Jaffrey NH

# stdlib
import logging

# third party
import ttkbootstrap as tkb
import pandas as pd

# local core
from m_wave.core.reporting import Reporting

# local wave pack
from m_wave.wave_packs.mtl.appender import DataAppender
from m_wave.wave_packs.mtl.extraction import DataExtractor
from m_wave.wave_packs.mtl.formatter import DataFormatter
from m_wave.wave_packs.mtl.comparisons import Comparisons
from m_wave.wave_packs.mtl.metadata import Metadata
from m_wave.wave_packs.mtl.utils import report_shape_differences

logger = logging.getLogger(__name__)


class Process:
    """
    This process shall attempt to extract MTL named tables and CSV input files into
    data frames. These extracted data frames will then be formatted and sorted
    according to the formatting style of the MTL.

    The comparison function shall attempt to compare the MTL to the input and report
    to the user if the comparison is sound or has differences. These differences shall
    be reported to the user in the form of log files and exported csv files of the data
    frames that were compared. This comparison shall be able to compare full MTL table
    data along with a user supplied 'filter' that shall attempt to filter each
    data frame.

    The append function shall attempt to append and update the MTL data frame with
    the input file. The appended or updated data, known as an upsert, shall be reported
    to the user with exported log and csv files. The append function shall attempt to
    apply these upserts to the MTL directly. The user will be  responsible for updating
    the change log manually.

    """

    def __init__(
        self,
        report: Reporting,
        filter_string: str,
        selected_data_table: str,
        mtl_file_path: str,
        input_file_path: str,
    ) -> None:
        self.filter_string = filter_string
        self.mtl_worksheet_name = selected_data_table
        self.mtl_file_path = mtl_file_path
        self.input_file_path = input_file_path

        self.report = report
        self.metadata = Metadata(self.report)
        self.metadata.set_worksheet_name(self.mtl_worksheet_name)
        self.metadata.set_table_type()

        self.data_appender = DataAppender(self.report, self.metadata)
        self.data_extractor = DataExtractor(self.report, self.metadata)
        self.data_formatter = DataFormatter(self.report, self.metadata)
        self.comparisons = Comparisons(self.report, self.metadata)

    def get_mtl_from_web(
        self, version_stringvar: tkb.StringVar, mtl_path_stringvar: tkb.StringVar
    ) -> bool:
        """
        A test process that attemps to pull the MTL directly from ManGo.
        """
        self.report.title("ATTEMPTING TO DOWNLOAD THE MTL FROM MANGO")
        try:
            mtl_path = self.data_extractor.download_mtl()
            self.report.info("MTL SUCCESSFULLY DOWNLOADED")
            if mtl_path is not None:
                self.mtl_file_path = str(mtl_path)
                mtl_path_stringvar.set(str(self.mtl_file_path))
                revision = self.data_extractor.get_last_revision(mtl_path)
                self.report.simple_title(f"Revision of the MTL: {revision}")
                version_stringvar.set(f"{revision}")
                self.metadata.set_mtl_version(str(revision))
            else:
                self.report.highlight_error("MTL PATH WAS NONE")
            return True
        except Exception as e:
            self.report.highlight_error(f"{e}")
            self.report.exception(f"{e}")
            return False
        finally:
            self.report.save_report()

    def _can_compare(self) -> bool:
        """
        Check a MTL worksheet by name and determine if it can be processed.
        """
        can_compare = self.metadata.can_compare_worksheet()
        if not can_compare:
            self.report.highlight_titled_error(
                "This table does not yet have the capability to process data.",
            )
            self.report.error("Stopping process...")
            return False
        return True

    def _save_as_csv(self, df: pd.DataFrame, filename: str) -> None:
        """
        Helper function to save the data frame content from before and after a process
        run.
        """
        save_path = self.report.report_folder / filename
        save_path = save_path.with_suffix(".csv")
        df.to_csv(save_path, encoding="utf-8", index=False)

    def run_comparison(self) -> bool:
        """
        Runs the comparison logic.
        """
        try:
            self.report.title(
                f"COMPARISON STARTED FOR WORKSHEET: {self.mtl_worksheet_name}"
            )
            self.report.subtitle(
                f"THIS REPORT WAS GENERATED BY {self.report.user} "
                + f"ON {self.report.timestamp_merck}"
            )
            # NOTE: FILTER STRING REPORTING
            if not self.filter_string:
                self.report.subtitle("THIS REPORT DID NOT USE A FILTER")
            else:
                self.report.subtitle(
                    f'THIS REPORT USED "{self.filter_string}" TO FILTER '
                    + f'"{self.mtl_worksheet_name}"'
                )

            # NOTE: META DATA COMPARISON CHECK
            if not self._can_compare():
                return False

            # NOTE: EXTRACTION PHASE
            self.report.simple_title("Extracting the Table from the MTL")
            mtl_df = self.data_extractor.extract_mtl_table(self.mtl_file_path)
            self.report.simple_title("Extracting the Table from the PI Builder input.")
            input_df = self.data_extractor.extract_input_csv(
                self.input_file_path, self.filter_string
            )

            if not self.data_extractor.could_extract(mtl_df, input_df):
                self.report.warning(
                    "Could not extract data sets. Process stopped.", popup=True
                )
                return False

            # NOTE: Data frame before snapshot
            self.report.simple_title("Taking a data snapshot...")
            self._save_as_csv(mtl_df, "mtl_data_before_formatting")
            self._save_as_csv(input_df, "input_data_before_formatting")

            # NOTE: FORMATTING PHASE
            self.report.simple_title("Formatting the MTL table.")
            mtl_df = self.data_formatter.format(mtl_df)
            self.report.simple_title("Formatting the PI Builder table.")
            input_df = self.data_formatter.format(input_df)

            # NOTE: COLUMN CONFORMING PHASE
            self.report.simple_title("Comparing columns and making adjustments")
            mtl_df, input_df = self.data_formatter.conform_columns(mtl_df, input_df)

            if mtl_df.empty or input_df.empty:
                self.report.warning(
                    "Could not align columns between the data sets. Process stopped. "
                    + "Check that you are using the correct PI Builder CSV.",
                    popup=True,
                )
                return False

            # NOTE: FILTERING PHASE
            if self.filter_string:
                self.report.simple_title(f"Filter detected: {self.filter_string}")
                self.report.simple_title("Filtering the MTL table.")
                mtl_df = self.data_formatter.filter_by_string(
                    mtl_df, self.filter_string
                )
                self.report.simple_title("Filtering the PI Builder table.")
                input_df = self.data_formatter.filter_by_string(
                    input_df, self.filter_string
                )

                if mtl_df.empty or input_df.empty:
                    self.report.warning(
                        "Data frames returned empty after trying to filter them.",
                        popup=True,
                    )
                    self.report.warning(
                        "This may not be an error, but a bad filter string. Check your logs for errors, or change your filter string.",
                        popup=True,
                    )
                    return False

            # NOTE: SORTING PHASE
            self.report.simple_title("Sorting the data frames per MTL table formatting")
            self.report.info("Sorting the MTL.")
            mtl_df = self.data_formatter.sort(mtl_df)
            self.report.info("Sorting the input.")
            input_df = self.data_formatter.sort(input_df)
            if mtl_df.empty or input_df.empty:
                self.report.warning(
                    "Could not sort the data frames! Stopping process.", popup=True
                )
                return False

            # NOTE: Data frame after snapshot
            self.report.simple_title("Taking a data snapshot...")
            self._save_as_csv(mtl_df, "mtl_data_after_formatting")
            self._save_as_csv(input_df, "input_data_after_formatting")

            # NOTE: COMPARISON AND REPORTING PHASE
            self.report.simple_title("Now running the comparison.")
            return self.comparisons.compare(mtl_df, input_df, self.data_formatter.sort)
        except Exception as e:
            self.report.exception(
                "There was an unexpected error during the comparison. "
                + f"Check the general logs.\n{e}"
            )
            return False
        finally:
            self.report.save_report()

    def run_append(self) -> bool:
        """
        Append the supplied PI builder data to the MTL/CMD.
        Returns False if process fails.
        """
        try:
            # NOTE: START APPENDING
            self.report.title(f"APPENDING MTL ON WORKSHEET: {self.mtl_worksheet_name}")
            self.report.subtitle(
                f"THIS REPORT WAS GENERATED BY {self.report.user} "
                + f"ON {self.report.timestamp_merck}"
            )
            # NOTE: FILTER STRING REPORTING
            if not self.filter_string:
                self.report.subtitle("THIS REPORT DID NOT USE A FILTER")
            else:
                self.report.subtitle(
                    f'THIS REPORT USED "{self.filter_string}" TO FILTER '
                    + f'"{self.mtl_worksheet_name}"'
                )

            # NOTE: EXTRACTION PHASE
            self.report.simple_title("Extracting the Table from the MTL")
            mtl_df = self.data_extractor.extract_mtl_table(self.mtl_file_path)
            self.report.simple_title("Extracting the Table from the PI Builder input.")
            input_df = self.data_extractor.extract_input_csv(
                self.input_file_path, self.filter_string
            )

            if not self.data_extractor.could_extract(mtl_df, input_df):
                self.report.warning(
                    "Could not extract data sets. Process stopped.", popup=True
                )
                return False

            # NOTE: Data frame before snapshot
            self.report.simple_title("Taking a data snapshot...")
            self._save_as_csv(mtl_df, "mtl_data_before_formatting")
            self._save_as_csv(input_df, "input_data_before_formatting")

            # NOTE: FORMATTING PHASE
            self.report.simple_title("Preparing data")

            # Format the data frames to the worksheet table type formats of the MTL.
            self.report.simple_title("Formatting MTL dataframe...")
            mtl_df = self.data_formatter.format(mtl_df)
            self.report.simple_title("Formatting INPUT CSV dataframe...")
            input_df = self.data_formatter.format(input_df)

            if not self.data_formatter.could_format(mtl_df, input_df):
                self.report.warning(
                    "Could not format the data sets. Process stopped.", popup=True
                )
                return False

            # NOTE: COLUMN CONFORMING PHASE
            self.report.simple_title("Comparing columns and making adjustments")
            mtl_df, input_df = self.data_formatter.conform_columns(
                mtl_df, input_df, use_version=True
            )

            if mtl_df.empty or input_df.empty:
                self.report.warning(
                    "Could not align columns between the data sets. Process stopped. "
                    + "Check that you are using the correct PI Builder CSV.",
                    popup=True,
                )
                return False

            # NOTE: FILTERING PHASE
            if self.filter_string:
                self.report.simple_title(f"Filter detected: {self.filter_string}")
                self.report.simple_title("Filtering the MTL table.")
                mtl_df = self.data_formatter.filter_by_string(
                    mtl_df, self.filter_string
                )
                self.report.simple_title("Filtering the PI Builder table.")
                input_df = self.data_formatter.filter_by_string(
                    input_df, self.filter_string
                )

                if mtl_df.empty or input_df.empty:
                    self.report.warning(
                        "Data frames returned empty after trying to filter them.",
                        popup=True,
                    )
                    self.report.warning(
                        "This may not be an error, but a bad filter string. Check your logs for errors, or change your filter string.",
                        popup=True,
                    )
                    return False

            # NOTE: SORTING PHASE
            self.report.simple_title("Sorting the data frames per MTL table formatting")
            self.report.info("Sorting the MTL.")
            mtl_df = self.data_formatter.sort(mtl_df)
            self.report.info("Sorting the input.")
            input_df = self.data_formatter.sort(input_df)
            if mtl_df.empty or input_df.empty:
                self.report.warning(
                    "Could not sort the data frames! Stopping process. Check your PI "
                    + "Builder file for any irregularities.",
                    popup=True,
                )
                return False

            # NOTE: Data frame after snapshot
            self.report.simple_title("Taking a data snapshot...")
            self._save_as_csv(mtl_df, "mtl_data_after_formatting")
            self._save_as_csv(input_df, "input_data_after_formatting")

            # NOTE: COMPARISON PHASE
            self.report.simple_title("General Data Frame Comparison Sanity Check")
            (
                mtl_rows,
                input_rows,
                _,
                _,
            ) = report_shape_differences(self.report, mtl_df, input_df)
            if mtl_rows == 0 or input_rows == 0:
                self.report.warning(
                    "No data found within the data frames where there should be data. Stopping process.",
                    popup=True,
                )
                return False

            # NOTE: APPEND PHASE
            self.report.simple_title("Appending and updating the MTL.")
            appended_dataframe = self.data_appender.upsert(mtl_df, input_df)
            if appended_dataframe.empty:
                self.report.warning(
                    "New appended data came back empty. Could not append data. "
                    + "Check your log files for errors.",
                    popup=True,
                )
                return False

            # NOTE: REPORT PHASE
            self.report.simple_title("Saving final data frame to CSV.")
            self.data_appender.export_to_csv(appended_dataframe)
            self.report.info(
                "Review the generated .LOG and CSV files for detailed results."
            )
            self.report.simple_title(
                "Attempting to create an appended version of the MTL."
            )
            self.report.warning("This may take take a moment...")
            self.data_appender.export_to_mtl(appended_dataframe, self.mtl_file_path)

            # FINALLY
            self.report.title("Appending completed.")
            return True

        except Exception as e:
            self.report.exception(
                f"Unexpected error during append logic:\n{e}", popup=True
            )
            return False

        finally:
            self.report.save_report()


if __name__ == "__main__":
    raise RuntimeError("Should not run this module as a script. Exiting.")
